# -*- coding: utf-8 -*-
"""TFM_Zakzuk_Codigo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nxlBXogwB-f0mRqjxJQLHItSifH28d7w

# TFM - Clasificación de Diabetes con Machine Learning
**Autor:** Alejandro Zakzuk  
**Máster en IA Aplicada a la Salud — CEMP**  
**Febrero 2026**

Este notebook contiene todo el codigo para mi TFM. El objetivo es comparar tres modelos de machine learning para clasificar pacientes diabéticos usando el dataset Pima Indians.
"""

# Primero importo todo lo que voy a necesitar
# Lo puse todo junto aquí arriba para tenerlo ordenado

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# esto es para los modelos
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

# métricas para evaluar
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, roc_curve,
    confusion_matrix
)

import shap
import joblib  # para guardar el modelo al final
import warnings
warnings.filterwarnings('ignore')

import kagglehub

# Download latest version
path = kagglehub.dataset_download("uciml/pima-indians-diabetes-database")

print("Path to dataset files:", path)
print('todo importado ok')

"""## 1. Carga de datos

El dataset que uso es el Pima Indians Diabetes Database. Tiene 768 pacientes (todas mujeres mayores de 21 años) con 8 variables clínicas y una variable objetivo que indica si tiene diabetes o no.
"""

import os

# el CSV de kaggle tiene cabecera así que salto la primera fila y asigno nombres manualmente
nombres_col = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness',
               'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Usa la ruta de kagglehub para cargar el archivo, saltando la primera fila que es la cabecera.
datos = pd.read_csv(os.path.join(path, 'diabetes.csv'), skiprows=1, names=nombres_col)

# a veces pandas lee columnas numéricas como object si hay inconsistencias al parsear, fuerzo conversión
for col in nombres_col:
    datos[col] = pd.to_numeric(datos[col], errors='coerce') # 'coerce' convertirá cualquier valor no numérico a NaN

print('dimensiones del dataset:', datos.shape)
print()
datos.head(10)

# miro los tipos de datos y si hay nulos
print(datos.dtypes)
print()
print('valores nulos por columna:')
print(datos.isnull().sum())

"""## 2. Detección de valores faltantes codificados como cero

Esto es algo que aprendí leyendo sobre el dataset: algunos valores que deberían ser imposibles fisiológicamente aparecen como cero. Por ejemplo, una glucosa de 0 o un IMC de 0 no tienen sentido clínico — esos ceros son en realidad datos que no se recogieron y fueron codificados así por error (o por convención de la época).

Las variables donde esto puede pasar son: Glucose, BloodPressure, SkinThickness, Insulin y BMI.
"""

# cuento cuántos ceros hay en las columnas que no deberían tenerlos
cols_con_ceros = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']

for col in cols_con_ceros:
    n = (datos[col] == 0).sum()
    pct = n / len(datos) * 100
    print(f'{col}: {n} ceros ({pct:.1f}%)')

"""Lo más llamativo es Insulin con casi un 49% de ceros y SkinThickness con casi un 30%. Esos no pueden ser valores reales.

## 3. División train/test

Antes de imputar los valores faltantes hay que dividir el dataset en entrenamiento y test. Esto es importante porque si imputo primero usando todo el dataset, estaría usando información del test para calcular las medianas, lo que contaminaría la evaluación (a esto se le llama data leakage).

Uso un 80% para entrenar y 20% para testear, con stratify=y para que la proporción de diabéticas sea igual en ambos conjuntos.
"""

features = nombres_col[:-1]  # todas menos Outcome

X = datos.drop('Outcome', axis=1).copy()
y = datos['Outcome'].copy()

# reemplazo los ceros por NaN antes del split para poder imputarlos después
for col in cols_con_ceros:
    X[col] = X[col].replace(0, np.nan)

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y   # esto asegura que la proporción de clases se mantiene
)

print(f'Train: {X_train.shape[0]} pacientes')
print(f'Test:  {X_test.shape[0]} pacientes')
print(f'Proporción diabéticas en train: {y_train.mean():.2%}')
print(f'Proporción diabéticas en test:  {y_test.mean():.2%}')

"""## 4. Imputación por mediana segmentada por clase

La estrategia de imputación que uso es reemplazar cada valor faltante por la mediana de esa variable, pero calculada por separado para pacientes diabéticas y no diabéticas. Esto es más preciso que usar la mediana global, porque los valores fisiológicos son distintos entre los dos grupos (por ejemplo, la glucosa media de una diabética es mayor que la de una no diabética, así que no tiene sentido imputar con la misma mediana para ambas).

Las medianas las calculo solo sobre los datos de entrenamiento.
"""

# guardo las medianas para poder usarlas también en test (y eventualmente en producción)
medianas_imputacion = {}

X_train_imp = X_train.copy()
X_test_imp  = X_test.copy()

for col in cols_con_ceros:
    medianas_imputacion[col] = {}
    for clase in [0, 1]:
        # calculo la mediana solo con los datos de train de esa clase
        mediana = X_train_imp.loc[y_train == clase, col].median()
        medianas_imputacion[col][clase] = mediana

        # aplico en train
        mask_train = (y_train == clase) & (X_train_imp[col].isna())
        X_train_imp.loc[mask_train, col] = mediana

        # aplico en test usando la mediana de train (no de test)
        mask_test = (y_test == clase) & (X_test_imp[col].isna())
        X_test_imp.loc[mask_test, col] = mediana

print('Medianas usadas para imputación (calculadas sobre train):')
for col, vals in medianas_imputacion.items():
    print(f'  {col}: No diabética={vals[0]:.1f}, Diabética={vals[1]:.1f}')

print()
print('NaN restantes en train:', X_train_imp.isna().sum().sum())
print('NaN restantes en test: ', X_test_imp.isna().sum().sum())

"""## 5. Análisis exploratorio (EDA)

Antes de entrenar los modelos quiero entender bien los datos. Hago estadísticos básicos, histogramas por clase y una matriz de correlación.
"""

# junto train y test imputados para el EDA (solo para visualizar, no para modelar)
df_viz = pd.concat([X_train_imp, X_test_imp])
df_viz['Outcome'] = pd.concat([y_train, y_test]).values

print('Estadísticos descriptivos:')
print(df_viz.describe().round(2))
print()
print('Distribución de la variable objetivo:')
print(df_viz['Outcome'].value_counts())
print(df_viz['Outcome'].value_counts(normalize=True).round(3))

# histogramas de cada variable separados por clase
# quiero ver si se distinguen bien los grupos

fig, axes = plt.subplots(2, 4, figsize=(18, 8))
fig.suptitle('Distribución de variables por clase diagnóstica', fontsize=14)

for col, ax in zip(features, axes.flatten()):
    for outcome_val, color, etiqueta in [(0, '#3498db', 'No diabética'), (1, '#e74c3c', 'Diabética')]:
        subconjunto = df_viz[df_viz['Outcome'] == outcome_val][col]
        ax.hist(subconjunto, bins=20, alpha=0.55, color=color, label=etiqueta)
    ax.set_title(col)
    ax.legend(fontsize=7)

plt.tight_layout()
plt.savefig('histogramas_clases.png', dpi=150)
plt.show()
plt.close()

# boxplots para las variables que visualmente parecen más discriminativas
# (según los histogramas: Glucose, BMI, Age, Insulin)

vars_importantes = ['Glucose', 'BMI', 'Age', 'Insulin']

fig, axes = plt.subplots(1, 4, figsize=(16, 5))
fig.suptitle('Comparación de variables principales por clase', fontsize=13)

for col, ax in zip(vars_importantes, axes):
    datos_0 = df_viz[df_viz['Outcome'] == 0][col]
    datos_1 = df_viz[df_viz['Outcome'] == 1][col]
    ax.boxplot([datos_0, datos_1], labels=['No diabética', 'Diabética'])
    ax.set_title(col)

plt.tight_layout()
plt.savefig('boxplots_variables.png', dpi=150)
plt.show()
plt.close()

# matriz de correlación - quiero ver qué variables están más relacionadas con el outcome

plt.figure(figsize=(10, 8))
corr = df_viz.corr()
sns.heatmap(corr, annot=True, fmt='.2f', cmap='RdBu_r', center=0, square=True)
plt.title('Matriz de correlación de Pearson')
plt.tight_layout()
plt.savefig('correlacion.png', dpi=150)
plt.show()
plt.close()

# la correlación más alta con Outcome es Glucose (como era de esperar clínicamente)
print('Correlación de cada variable con Outcome:')
print(corr['Outcome'].sort_values(ascending=False).round(3))

"""## 6. Escalado de variables

LR y SVM necesitan los datos en la misma escala para que el optimizador no se vea sesgado por la magnitud de las variables. Uso StandardScaler. RF no lo necesita pq trabaja con particiones en los árboles, no con distancias.
"""

scaler = StandardScaler()

# fit solo sobre train, transform sobre ambos
# importante: si hiciera fit sobre todo el dataset también habría data leakage
X_train_sc = scaler.fit_transform(X_train_imp)
X_test_sc  = scaler.transform(X_test_imp)

# convierto a DataFrame para que sea más fácil de manejar
X_train_sc = pd.DataFrame(X_train_sc, columns=features)
X_test_sc  = pd.DataFrame(X_test_sc,  columns=features)

print('Escalado aplicado.')
print('Media tras escalar (debe ser ~0):')
print(X_train_sc.mean().round(3))

"""## 7. Entrenamiento y optimización de modelos

Comparo tres modelos que representan paradigmas distintos: LR como baseline lineal e interpretable, SVM con RBF para capturar no linealidades, y RF como ensemble robusto. Para cada uno hago búsqueda de hiperparámetros con GridSearchCV y validación cruzada estratificada de 5 folds sobre train.
"""

# defino el esquema de validacion cruzada que usaré dentro del GridSearch
# stratified para mantener proporción de clases en cada fold
cv_busqueda = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# y otro para la validacion cruzada final de 10 folds (como en el TFM)
cv_evaluacion = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

# --- REGRESIÓN LOGÍSTICA ---
# busco C óptimo con GridSearch; class_weight='balanced' para compensar el desbalance 65/35

params_lr = {'C': [0.01, 0.1, 1.0, 10.0]}

lr_base = LogisticRegression(
    solver='lbfgs',
    max_iter=1000,
    class_weight='balanced',
    random_state=42
)

busqueda_lr = GridSearchCV(lr_base, params_lr, cv=cv_busqueda, scoring='roc_auc', n_jobs=-1)
busqueda_lr.fit(X_train_sc, y_train)

mejor_lr = busqueda_lr.best_estimator_
print(f'LR - mejores params: {busqueda_lr.best_params_}  |  AUC CV: {busqueda_lr.best_score_:.4f}')

# --- SVM ---
# busco C y gamma; RBF porque espero fronteras no lineales en datos fisiológicos

params_svm = {
    'C': [1, 10, 100],
    'gamma': ['scale', 'auto']
}

svm_base = SVC(
    kernel='rbf',
    class_weight='balanced',
    probability=True,   # necesario para calcular AUC después
    random_state=42
)

busqueda_svm = GridSearchCV(svm_base, params_svm, cv=cv_busqueda, scoring='roc_auc', n_jobs=-1)
busqueda_svm.fit(X_train_sc, y_train)

mejor_svm = busqueda_svm.best_estimator_
print(f'SVM - mejores params: {busqueda_svm.best_params_}  |  AUC CV: {busqueda_svm.best_score_:.4f}')

# --- RANDOM FOREST ---
# busco n_estimators, max_depth y min_samples_split; min_samples_leaf=2 lo dejo fijo

params_rf = {
    'n_estimators': [100, 200],
    'max_depth': [5, 10, None],
    'min_samples_split': [2, 5]
}

rf_base = RandomForestClassifier(
    min_samples_leaf=2,
    class_weight='balanced',
    random_state=42
)

# el RF no necesita los datos escalados
busqueda_rf = GridSearchCV(rf_base, params_rf, cv=cv_busqueda, scoring='roc_auc', n_jobs=-1)
busqueda_rf.fit(X_train_imp, y_train)

mejor_rf = busqueda_rf.best_estimator_
print(f'RF - mejores params: {busqueda_rf.best_params_}  |  AUC CV: {busqueda_rf.best_score_:.4f}')

"""## 8. Evaluación en el conjunto de test

Ahora evalúo los modelos ya entrenados sobre el conjunto de test (el 20% que no se usó en ningún momento del entrenamiento). Calculo todas las métricas relevantes.
"""

# armo una lista con los tres modelos y sus datos correspondientes
# LR y SVM usan datos escalados, RF usa los datos sin escalar

configs_modelos = [
    ('Regresion Logistica', mejor_lr,  X_train_sc,  X_test_sc),
    ('SVM (RBF)',           mejor_svm, X_train_sc,  X_test_sc),
    ('Random Forest',      mejor_rf,  X_train_imp, X_test_imp),
]

resultados = {}

for nombre, modelo, X_tr, X_te in configs_modelos:

    y_pred = modelo.predict(X_te)
    y_prob = modelo.predict_proba(X_te)[:, 1]

    # calculo la curva ROC - devuelve tres cosas: fpr, tpr y umbrales
    fpr, tpr, umbrales_roc = roc_curve(y_test, y_prob)

    # validación cruzada sobre train para ver si el modelo generaliza
    scores_cv = cross_val_score(modelo, X_tr, y_train, cv=cv_evaluacion, scoring='roc_auc')

    resultados[nombre] = {
        'y_pred'   : y_pred,
        'y_prob'   : y_prob,
        'accuracy' : accuracy_score(y_test, y_pred),
        'precision': precision_score(y_test, y_pred),
        'recall'   : recall_score(y_test, y_pred),
        'f1'       : f1_score(y_test, y_pred),
        'auc'      : roc_auc_score(y_test, y_prob),
        'cv_media' : scores_cv.mean(),
        'cv_std'   : scores_cv.std(),
        'cm'       : confusion_matrix(y_test, y_pred),
        'fpr'      : fpr,
        'tpr'      : tpr,
    }

    print(f'{nombre}: Acc={resultados[nombre]["accuracy"]:.4f}  '
          f'Recall={resultados[nombre]["recall"]:.4f}  '
          f'AUC={resultados[nombre]["auc"]:.4f}  '
          f'CV={scores_cv.mean():.4f}(+/-{scores_cv.std():.4f})')

# tabla resumen con todas las métricas
tabla = []
for nombre, res in resultados.items():
    tabla.append({
        'Modelo'    : nombre,
        'Accuracy'  : round(res['accuracy'],  4),
        'Precision' : round(res['precision'], 4),
        'Recall'    : round(res['recall'],    4),
        'F1'        : round(res['f1'],        4),
        'AUC'       : round(res['auc'],       4),
        'CV AUC'    : f"{res['cv_media']:.4f} ± {res['cv_std']:.4f}"
    })

df_resultados = pd.DataFrame(tabla)
print(df_resultados.to_string(index=False))

"""## 9. Curvas ROC"""

plt.figure(figsize=(8, 7))

colores = ['#3498db', '#e74c3c', '#2ecc71']

for (nombre, res), color in zip(resultados.items(), colores):
    plt.plot(
        res['fpr'], res['tpr'],
        label=f"{nombre} (AUC = {res['auc']:.3f})",
        lw=2, color=color
    )

plt.plot([0,1], [0,1], 'k--', alpha=0.4, label='Clasificador aleatorio')
plt.xlabel('Tasa de Falsos Positivos (1 - Especificidad)')
plt.ylabel('Sensibilidad (Recall)')
plt.title('Curvas ROC - Comparación de modelos')
plt.legend(loc='lower right')
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig('curvas_roc.png', dpi=150)
plt.show()
plt.close()

"""## 10. Matrices de confusión

Las matrices de confusión me permiten ver exactamente cuántos falsos negativos (FN) tiene cada modelo. En el contexto de cribado de diabetes, los FN son el peor error posible: son pacientes diabéticas que el modelo clasifica como sanas y que se quedan sin diagnóstico.
"""

fig, axes = plt.subplots(1, 3, figsize=(16, 5))
fig.suptitle('Matrices de Confusión - Conjunto de Test', fontsize=13)

for (nombre, res), ax in zip(resultados.items(), axes):
    sns.heatmap(
        res['cm'],
        annot=True, fmt='d', ax=ax,
        cmap='Blues',
        xticklabels=['No diabética', 'Diabética'],
        yticklabels=['No diabética', 'Diabética']
    )
    ax.set_title(nombre)
    ax.set_ylabel('Real')
    ax.set_xlabel('Predicción')

plt.tight_layout()
plt.savefig('matrices_confusion.png', dpi=150)
plt.show()
plt.close()

"""## 11. Importancia de variables - Random Forest

El Random Forest permite ver qué variables fueron más relevantes para las predicciones. Esto es útil para verificar que el modelo está usando variables que tienen sentido clínico y no está aprendiendo correlaciones espurias.
"""

importancias = pd.Series(
    mejor_rf.feature_importances_,
    index=features
).sort_values(ascending=True)

plt.figure(figsize=(9, 6))
importancias.plot(kind='barh', color='#3498db', edgecolor='white')
plt.title('Importancia de variables - Random Forest (Gini)')
plt.xlabel('Importancia relativa')
plt.tight_layout()
plt.savefig('importancia_variables.png', dpi=150)
plt.show()
plt.close()

print('Ranking:')
for feat, imp in importancias.sort_values(ascending=False).items():
    print(f'  {feat}: {imp:.4f}')

"""## 12. Análisis del umbral de decisión

Por defecto los clasificadores usan un umbral de 0.5: si la probabilidad predicha es mayor de 0.5, clasifica como diabética. Pero en contexto de cribado clínico puede interesar bajar ese umbral para detectar más casos verdaderos (aunque se generen más falsos positivos). Un falso positivo en cribado significa pedir una HbA1c confirmatoria, que es un coste asumible. Un falso negativo significa dejar a una diabética sin diagnóstico durante años.

Aquí analizo qué pasa con las métricas al variar el umbral.
"""

probs_rf = resultados['Random Forest']['y_prob']

print(f'Análisis de umbral para Random Forest:\n')
print(f'{"Umbral":>8}  {"Sensibilidad":>13}  {"Especificidad":>14}  {"Accuracy":>10}  {"F1":>8}')
print('-' * 60)

for umbral in [0.30, 0.35, 0.40, 0.45, 0.50, 0.55, 0.60]:
    y_u = (probs_rf >= umbral).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_test, y_u).ravel()

    sens = tp / (tp + fn)
    spec = tn / (tn + fp)
    acc  = accuracy_score(y_test, y_u)
    f1   = f1_score(y_test, y_u)

    print(f'{umbral:>8.2f}  {sens:>13.4f}  {spec:>14.4f}  {acc:>10.4f}  {f1:>8.4f}')

"""## 13. Explicabilidad con SHAP

SHAP (SHapley Additive exPlanations) permite ver cómo contribuye cada variable a la predicción de cada paciente individual. Es importante para la confianza clínica: quiero verificar que el modelo da más peso a variables como Glucose o BMI, que tienen sentido fisiopatológico, y no a variables aleatorias.

El summary plot global muestra, para cada variable, cuánto y en qué dirección contribuye a las predicciones del conjunto de test.
"""

explicador = shap.TreeExplainer(mejor_rf)

# calculo los valores SHAP para el conjunto de test
shap_vals = explicador(X_test_imp)

# summary plot - clase 1 (diabética)
plt.figure()
shap.summary_plot(
    shap_vals[:, :, 1],
    X_test_imp,
    feature_names=features,
    show=False
)
plt.title('SHAP - Contribución de variables (clase: Diabética)')
plt.tight_layout()
plt.savefig('shap_summary.png', dpi=150)
plt.show()
plt.close()

# ejemplo de explicación individual para el paciente con mayor probabilidad predicha
# esto es lo que mencioné en el cap 5 del TFM sobre explicabilidad local

idx_mayor_riesgo = probs_rf.argmax()

plt.figure()
shap.waterfall_plot(shap_vals[idx_mayor_riesgo, :, 1], show=False)
plt.tight_layout()
plt.savefig('shap_waterfall.png', dpi=150)
plt.show()
plt.close()

print(f'Paciente #{idx_mayor_riesgo} - probabilidad predicha: {probs_rf[idx_mayor_riesgo]:.4f}')